version: '1'

setup:
  image: us.icr.io/otc-ops/otc-deploy:dev
  image_pull_policy: Always
  script: |
    #!/usr/bin/env bash
    source ./cd/setup.sh

test:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.12@sha256:ff4053b0bca784d6d105fee1d008cfb20db206011453071e86b69ca3fde706a4
  script: |
    #!/usr/bin/env bash
    echo "No unit tests for umbrella"

containerize:
  dind: true
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.12@sha256:ff4053b0bca784d6d105fee1d008cfb20db206011453071e86b69ca3fde706a4
  script: |
    #!/usr/bin/env bash
    echo "No image for umbrella"

scan-artifact:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.12@sha256:ff4053b0bca784d6d105fee1d008cfb20db206011453071e86b69ca3fde706a4
  script: |
    #!/usr/bin/env bash
    echo "No image to scan for umbrella"

sign-artifact:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.12@sha256:ff4053b0bca784d6d105fee1d008cfb20db206011453071e86b69ca3fde706a4
  script: |
    #!/usr/bin/env bash
    echo "No image to sign for umbrella"

deploy:
  image: us.icr.io/otc-ops/otc-deploy:dev
  image_pull_policy: Always
  script: |
    #!/usr/bin/env bash
    source ./cd/deploy.sh

acceptance-test:
  abort_on_failure: false
  image: us.icr.io/otc-ops/otc-deploy:dev
  image_pull_policy: Always
  script: |
    #!/usr/bin/env bash
    source ./cd/acceptance_test.sh

release:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.12@sha256:ff4053b0bca784d6d105fee1d008cfb20db206011453071e86b69ca3fde706a4
  script: |
    #!/usr/bin/env bash
    echo "TODO: save to inventory"
