# Documentation on available configuration
# https://pages.github.ibm.com/one-pipeline/docs/custom-scripts.html

version: '1'

setup:
  image: ibmcom/pipeline-base-image:2.9
  script: |
    #!/usr/bin/env bash

    # TODO

deploy:
  #image: ibmcom/pipeline-base-image:2.6
  image: us.icr.io/otc-ops/otc-deploy:test
  imagePullPolicy: Always
  script: |
    #!/usr/bin/env bash

    # config
    export ENVIRONMENT=$(cat /config/environment-properties/ENVIRONMENT)
    export INVENTORY_BRANCH=$(cat /config/environment-properties/target-environment)
    export PIPELINE_TOOLCHAIN_ID=$(jq -r '.toolchain_guid' /toolchain/toolchain.json)
    export IDS_JOB_ID=$PIPELINE_RUN_ID
    export IDS_USER=idsorg
    export REGISTRY_TOKEN_ID="10d3bc02-1aa0-5f94-a42a-92208f626af9"
    export OTC_REGISTRY=registry.ng.bluemix.net
    export CHART_REPO="devops-prod"
    export CHART_BRANCH="umbrella-$ENVIRONMENT"
    export PRUNE_CHART_REPO="true"
    export DOMAIN="$ENVIRONMENT.devops.cloud.ibm.com"
    export NAMESPACE=opentoolchain
    export WAIT_FOR_DEPLOY="true"
    export WAIT_FOR_DEPLOY_MAX="80"
    if [ -f /config/environment-properties/EXCLUDED_FROM_STATUS_CHECK ]; then
      export EXCLUDED_FROM_STATUS_CHECK=$(cat /config/environment-properties/EXCLUDED_FROM_STATUS_CHECK)
    fi
    if [ -f /config/environment-properties/DRY_RUN ]; then
      export DRY_RUN=$(cat /config/environment-properties/DRY_RUN)
    fi
    if [ -f /config/environment-properties/SKIP_CLUSTER_DANCE ]; then
      export SKIP_CLUSTER_DANCE=$(cat /config/environment-properties/SKIP_CLUSTER_DANCE)
    fi
    export DEPLOYMENT_SLACK_CHANNEL_ID=$(cat /config/environment-properties/DEPLOYMENT_SLACK_CHANNEL_ID)

    # secrets
    export IDS_TOKEN=$(cat /config/secure-properties/git-token)
    export IC_1308775_API_KEY=$(cat /config/secure-properties/IC_1308775_API_KEY)
    export IC_1651315_API_KEY=$(cat /config/secure-properties/IC_1651315_API_KEY)
    export OTC_REGISTRY_API_KEY=$(cat /config/secure-properties/IC_1416501_API_KEY)
    export DEPLOYMENT_SLACK_TOKEN=$(cat /config/secure-properties/DEPLOYMENT_SLACK_TOKEN)

    # uncomment below if not using otc-deploy image
    # git clone https://$IDS_USER:$IDS_TOKEN@github.ibm.com/org-ids/otc-deploy
    # cp -r otc-deploy/k8s/scripts/* /
    # git clone "https://$IDS_USER:$IDS_TOKEN@github.ibm.com/ids-env/devops-config"
    # cp -r devops-config/otc-deploy/* /config

    . /umbrella/helpers.sh
    buildAndDeployFromInventory $ENVIRONMENT $INVENTORY_BRANCH $DEPLOYMENT_SLACK_CHANNEL_ID $DEPLOYMENT_SLACK_TOKEN $SKIP_CLUSTER_DANCE

acceptance-test:
  image: us.icr.io/otc-ops/otc-deploy:test
  imagePullPolicy: Always
  script: |
    #!/usr/bin/env bash
    export ENVIRONMENT=$(cat /config/environment-properties/ENVIRONMENT)
    export TEST_PIPELINE_ID=$(cat /config/environment-properties/TEST_PIPELINE_ID)
    export IC_1651315_API_KEY=$(cat /config/secure-properties/IC_1651315_API_KEY)
    . /umbrella/helpers.sh
    runRegionTests status "$ENVIRONMENT" "$PIPELINE_RUN_ID" "d5c0676c-55ed-4c25-b763-60b7afd64c87" "$TEST_PIPELINE_ID"
    echo "Status of $ENVIRONMENT tests is $status"
    if [ "$status" != "succeeded" ]; then
      exit 1
    fi