# Documentation on available configuration
# https://pages.github.ibm.com/one-pipeline/docs/custom-scripts.html

version: '1'

setup:
  image: ibmcom/pipeline-base-image:2.9
  script: |
    #!/usr/bin/env bash

    # TODO

deploy:
  #image: ibmcom/pipeline-base-image:2.6
  image: us.icr.io/otc-ops/otc-deploy:test
  imagePullPolicy: Always
  script: |
    #!/usr/bin/env bash

    # config
    export ENVIRONMENT=$(cat /config/environment-properties/ENVIRONMENT)
    export INVENTORY_BRANCH=$(cat /config/environment-properties/target-environment)
    export PIPELINE_TOOLCHAIN_ID=$(jq -r '.toolchain_guid' /toolchain/toolchain.json)
    export IDS_JOB_ID=$PIPELINE_RUN_ID
    export IDS_USER=idsorg
    export REGISTRY_TOKEN_ID="10d3bc02-1aa0-5f94-a42a-92208f626af9"
    export OTC_REGISTRY=registry.ng.bluemix.net
    export CHART_REPO="devops-prod"
    export CHART_BRANCH="umbrella-$ENVIRONMENT"
    export PRUNE_CHART_REPO="true"
    export DOMAIN="$ENVIRONMENT.devops.cloud.ibm.com"
    export NAMESPACE=opentoolchain
    export WAIT_FOR_DEPLOY="true"
    export WAIT_FOR_DEPLOY_MAX="80"
    if [ -f /config/environment-properties/EXCLUDED_FROM_STATUS_CHECK ]; then
      export EXCLUDED_FROM_STATUS_CHECK=$(cat /config/environment-properties/EXCLUDED_FROM_STATUS_CHECK)
    fi
    if [ -f /config/environment-properties/DRY_RUN ]; then
      export DRY_RUN=$(cat /config/environment-properties/DRY_RUN)
    fi
    if [ -f /config/environment-properties/SKIP_CLUSTER_DANCE ]; then
      export SKIP_CLUSTER_DANCE=$(cat /config/environment-properties/SKIP_CLUSTER_DANCE)
    fi
    export DEPLOYMENT_SLACK_CHANNEL_ID=$(cat /config/environment-properties/DEPLOYMENT_SLACK_CHANNEL_ID)

    # secrets
    export IDS_TOKEN=$(cat /config/secure-properties/git-token)
    export IC_1308775_API_KEY=$(cat /config/secure-properties/IC_1308775_API_KEY)
    export IC_1651315_API_KEY=$(cat /config/secure-properties/IC_1651315_API_KEY)
    export OTC_REGISTRY_API_KEY=$(cat /config/secure-properties/IC_1416501_API_KEY)
    export DEPLOYMENT_SLACK_TOKEN=$(cat /config/secure-properties/DEPLOYMENT_SLACK_TOKEN)

    # uncomment below if not using otc-deploy image
    # git clone https://$IDS_USER:$IDS_TOKEN@github.ibm.com/org-ids/otc-deploy
    # cp -r otc-deploy/k8s/scripts/* /
    # git clone "https://$IDS_USER:$IDS_TOKEN@github.ibm.com/ids-env/devops-config"
    # cp -r devops-config/otc-deploy/* /config

    # build umbrella chart
    . /umbrella/buildUmbrellaChartFromInventory.sh $INVENTORY_BRANCH

    # get clusters
    readEnvironmentInfo envInfo $ENVIRONMENT "otc"
    if [ -z "$envInfo" ]; then 
        return 1; 
    fi
    getUmbrellaClusters clusters "$envInfo"

    # split first cluster and other clusters
    firstCluster=$(echo $clusters | awk '{print $1}')
    otherClusters=$(echo $clusters | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}')

    # deploy to first cluster
    if [ "$SKIP_CLUSTER_DANCE" != "true" ]; then
      . /glb/clusterDance.sh "($firstCluster)" "()"
    fi
    echo "Deploying to $firstCluster"
    echo
    . /umbrella/deployHelmChart.sh $firstCluster
    echo "Done deploying to $firstCluster"
    echo
    echo "Running health check for $firstCluster"
    . /cluster-checks/sanityCheckAll.sh $firstCluster
    echo "Done running heath check for $firstCluster"
    echo
    if [ "$SKIP_CLUSTER_DANCE" != "true" ]; then
      . /glb/clusterDance.sh "($otherClusters)" "($firstCluster)"
    fi

    if [ "$DEPLOYMENT_SLACK_CHANNEL_ID" != "ignore" ]; then
      echo "Waiting for $firstCluster testing to complete" 
      postSlackMessage timestamp "Please test/check the ui/logs for $firstCluster :fidg-spinn: = testing and :+1: = complete" $DEPLOYMENT_SLACK_CHANNEL_ID $DEPLOYMENT_SLACK_TOKEN
      waitForSlackGoNoGo go $timestamp $DEPLOYMENT_SLACK_CHANNEL_ID $DEPLOYMENT_SLACK_TOKEN
      if [ "$go" == "-1" ]; then
        echo "Got a no go to proceed after testing $firstCluster"
        echo "Aborting"
        exit -1
      fi
      echo "$firstCluster testing complete"
      echo
    fi

    # deploy to other clusters
    for cluster_name in "$otherClusters"; do 
      echo "Deploying to $cluster_name"
      echo
      . /umbrella/deployHelmChart.sh $cluster_name
      echo "Done deploying to $cluster_name"
      echo
      echo "Running health check for $cluster_name"
      . /cluster-checks/sanityCheckAll.sh $cluster_name
      echo "Done running heath check for $cluster_name"
      echo
     done
    if [ "$SKIP_CLUSTER_DANCE" != "true" ]; then
      . /glb/clusterDance.sh "()" "($otherClusters)"
    fi

acceptance-test:
  image: us.icr.io/otc-ops/otc-deploy:test
  imagePullPolicy: Always
  script: |
    #!/usr/bin/env bash
    export ENVIRONMENT=$(cat /config/environment-properties/ENVIRONMENT)
    export IC_1651315_API_KEY=$(cat /config/secure-properties/IC_1651315_API_KEY)
    . /umbrella/helpers.sh
    runRegionTests status "$ENVIRONMENT" "$PIPELINE_RUN_ID" "d5c0676c-55ed-4c25-b763-60b7afd64c87" "0a86e449-cd54-4ccf-9704-28eb39c02a13"
