version: '1'

setup:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.21@sha256:4ce661dc331005bc3cb828a677c760b2dda3c2951415141a91aeb0c0b9a351da
  script: |
    #!/usr/bin/env bash
    source ./cc/setup.sh

static-scan:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.21@sha256:4ce661dc331005bc3cb828a677c760b2dda3c2951415141a91aeb0c0b9a351da
  script: |
    #!/usr/bin/env bash
    source ./cc/static_scan.sh

scan-artifact:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.21@sha256:4ce661dc331005bc3cb828a677c760b2dda3c2951415141a91aeb0c0b9a351da
  script: |
    #!/usr/bin/env bash
    source ./cc/scan_artifact.sh

dynamic-scan:
  dind: true
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.21@sha256:4ce661dc331005bc3cb828a677c760b2dda3c2951415141a91aeb0c0b9a351da
  script: |
    #!/usr/bin/env bash
    source ./cc/dynamic_api_scan.sh

