# Documentation on available configuration
# https://pages.github.ibm.com/one-pipeline/docs/custom-scripts.html

version: '1'

setup:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.21@sha256:4ce661dc331005bc3cb828a677c760b2dda3c2951415141a91aeb0c0b9a351da
  script: |
    #!/usr/bin/env bash
    source ./cd/setup.sh
    
deploy:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.21@sha256:4ce661dc331005bc3cb828a677c760b2dda3c2951415141a91aeb0c0b9a351da
  script: |
    #!/usr/bin/env bash
    source ./cd/deploy.sh

acceptance-test:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.21@sha256:4ce661dc331005bc3cb828a677c760b2dda3c2951415141a91aeb0c0b9a351da
  script: |
    #!/usr/bin/env bash
    source ./cd/acceptance_test.sh
