# Documentation on available configuration
# https://pages.github.ibm.com/one-pipeline/docs/custom-scripts.html

version: '1'

setup:
  image: us.icr.io/otc-ops/otc-deploy:dev
  image_pull_policy: Always
  script: |
    #!/usr/bin/env bash
    source ./cd/setup.sh
    
deploy:
  image: us.icr.io/otc-ops/otc-deploy:dev
  image_pull_policy: Always
  script: |
    #!/usr/bin/env bash
    source ./cd/deploy.sh

acceptance-test:
  image: us.icr.io/otc-ops/otc-deploy:dev
  image_pull_policy: Always
  script: |
    #!/usr/bin/env bash
    source ./cd/acceptance_test.sh