version: '1'

setup:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.21@sha256:4ce661dc331005bc3cb828a677c760b2dda3c2951415141a91aeb0c0b9a351da
  script: |
    #!/usr/bin/env bash
    source ./ci/common/setup.sh CI

test:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.21@sha256:4ce661dc331005bc3cb828a677c760b2dda3c2951415141a91aeb0c0b9a351da
  script: |
    #!/usr/bin/env bash
    echo "Not running tests for dynamic scan pipeline"

containerize:
  dind: true
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.21@sha256:4ce661dc331005bc3cb828a677c760b2dda3c2951415141a91aeb0c0b9a351da
  script: |
    #!/usr/bin/env bash
    source ./ci/common/containerize.sh

scan-artifact:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.21@sha256:4ce661dc331005bc3cb828a677c760b2dda3c2951415141a91aeb0c0b9a351da
  script: |
    #!/usr/bin/env bash
    echo "Not scanning artifact for dynamic scan pipeline"

sign-artifact:
  abort_on_failure: false
  image: wcp-compliance-automation-team-docker-local.artifactory.swg-devops.com/csso-image-sign@sha256:cb22e6ad6b3469155719f6bf09bde641208a1e349e5ccc09407204bb069f7b4e
  script: |
    #!/usr/bin/env bash
    source ./ci/common/sign_artifact.sh

deploy:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.21@sha256:4ce661dc331005bc3cb828a677c760b2dda3c2951415141a91aeb0c0b9a351da
  script: |
    #!/usr/bin/env bash
    source ./ci/common/deploy.sh

dynamic-scan:
  dind: true
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.21@sha256:4ce661dc331005bc3cb828a677c760b2dda3c2951415141a91aeb0c0b9a351da
  script: |
    #!/usr/bin/env bash
    source ./ci/common/dynamic_api_scan.sh

acceptance-test:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.21@sha256:4ce661dc331005bc3cb828a677c760b2dda3c2951415141a91aeb0c0b9a351da
  script: |
    #!/usr/bin/env bash
    echo "Not running tests for dynamic scan pipeline"

release:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.21@sha256:4ce661dc331005bc3cb828a677c760b2dda3c2951415141a91aeb0c0b9a351da
  script: |
    #!/usr/bin/env bash 
    echo "Not running release for dynamic scan pipeline" # dynamic scan evidences will be overriden by regular ci pipeline, so no need to save them here
    #APP_NAME=$(get_env app-name)
    #source ./ci/common/release.sh "Nightly dynamic scan for $APP_NAME"
