version: '1'

setup:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.11
  script: |
    #!/usr/bin/env bash
    source ./ci/common/setup.sh

test:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.11
  script: |
    #!/usr/bin/env bash
    source ./ci/common/test.sh

containerize:
  dind: true
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.11
  script: |
    #!/usr/bin/env bash
    source ./ci/common/containerize.sh

deploy:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.11
  script: |
    #!/usr/bin/env bash
    source ./ci/common/deploy.sh

acceptance-test:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.11
  script: |
    #!/usr/bin/env bash
    source ./ci/common/acceptance_test.sh

release:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.8
  script: |
    #!/usr/bin/env bash
    source ./ci/common/release.sh

