version: '1'

setup:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.7@sha256:282677e79ccb9d20c699d384a54093894de03675752cd848a3133266c898c14c
  script: |
    #!/usr/bin/env bash
    echo "WORKSPACE=$WORKSPACE"
    GH_TOKEN=$(cat "$WORKSPACE/git-token")
    OWNER=$(jq -r '.services[] | select(.toolchain_binding.name=="app-repo") | .parameters.owner_id' /toolchain/toolchain.json)
    REPO=$(jq -r '.services[] | select(.toolchain_binding.name=="app-repo") | .parameters.repo_name' /toolchain/toolchain.json)
    curl -u ":$GH_TOKEN" https://github.ibm.com/api/v3/repos/$OWNER/$REPO/branches/master/protection -XPUT -d '{"required_pull_request_reviews":{"dismiss_stale_reviews":true},"required_status_checks":{"strict":true,"contexts":["tekton/code-branch-protection","tekton/code-unit-tests","tekton/code-cis-check","tekton/code-vulnerability-scan","tekton/code-detect-secrets"]},"enforce_admins":null,"restrictions":null}'
    APP_NAME=$(cat /config/app-name)
    git clone https://$GH_TOKEN@github.ibm.com/$OWNER/$REPO $APP_NAME
    cd $APP_NAME

    #source ../ci/common/code_setup.sh

test:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.7@sha256:282677e79ccb9d20c699d384a54093894de03675752cd848a3133266c898c14c
  script: |
    #!/usr/bin/env bash
    cd $(cat /config/app-name)

    #source ../ci/common/tests.sh

containerize:
  dind: true
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.6@sha256:7f588468622a981f89cf5e1212aaf75fface9da6169b5345ca52ab63d8215907
  script: |
    #!/usr/bin/env bash

    if [[ "$PIPELINE_DEBUG" == 1 ]]; then
      trap env EXIT
      env
      set -x
    fi
    cd $(cat /config/app-name)

    if false; then
      source ../ci/common/build_setup.sh
      source ../ci/common/build.sh
    else
      echo sha256:fcb67782542310dc8cce0dd59c9df08b1f8b0dbd2e235b4e572ede4f9b8bebdf > ../../image-digest
      echo 20210210145430-master-4ce89e59127a7760b2ebf94c7d50929ec82de05a > ../../image-tags
      echo us.icr.io/opentoolchain/otc-pagerduty-broker:20210210145430-master-4ce89e59127a7760b2ebf94c7d50929ec82de05a > ../../image
      echo IMAGE_REGISTRY=us.icr.io > build.properties
      echo REGISTRY_NAMESPACE=opentoolchain >> build.properties
      echo IMAGE_NAME=otc-pagerduty-broker >> build.properties
      echo REGISTRY_URL=us.icr.io/opentoolchain >> build.properties
      echo APPLICATION_VERSION=20210210145430-master-4ce89e59127a7760b2ebf94c7d50929ec82de05a >> build.properties
      echo BUILD_NUMBER=63 >> build.properties
    fi

deploy:
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.6@sha256:7f588468622a981f89cf5e1212aaf75fface9da6169b5345ca52ab63d8215907
  script: |
    #!/usr/bin/env bash
    if [[ "$PIPELINE_DEBUG" == 1 ]]; then
      trap env EXIT
      env
      set -x
    fi
    cd $(cat /config/app-name)

    #source ../ci/common/deploy_setup.sh
    #source ../ci/common/deploy.sh

acceptance-test:
  abort_on_failure: false
  image: icr.io/continuous-delivery/pipeline/pipeline-base-image:2.7@sha256:282677e79ccb9d20c699d384a54093894de03675752cd848a3133266c898c14c
  script: |
    #!/usr/bin/env bash
    cd $(cat /config/app-name)

    source ../ci/common/acceptance_tests.sh

release:
  image: wcp-compliance-automation-team-docker-local.artifactory.swg-devops.com/ibm-compliance-automation:1.2.4@sha256:dc98cc52c0caede42149c08727147520e30e81fee543b8dd5939b45d06baa142
  script: |
    #!/usr/bin/env bash
    cd $(cat /config/app-name)

    #source ../ci/common/release.sh

