#!/usr/bin/env bash

# to pass helm lint --strict
export SEC_AMPLITUDE_API_KEY=topasshelmlintstrict
export SEC_CLOUDANT_IAM_API_KEY=topasshelmlintstrict
export SEC_CLOUDANT_IAM_CLIENT_SECRET_METRICS_AMPLITUDE=topasshelmlintstrict
export ENV_ARGS=topasshelmlintstrict
export ENV_BLUEMIX_REGION=topasshelmlintstrict
export ENV_CLOUDANT_URL=topasshelmlintstrict
export ENV_CLOUDANT_IAM_CLIENT_ID_METRICS_SETUP=topasshelmlintstrict
export ENV_METRICS_EVENTS_DB_NAME=topasshelmlintstrict
export ENV_METRICS_WAREHOUSE_DB_NAME=topasshelmlintstrict
export ENV_OTC_API_DB_NAME=topasshelmlintstrict
export ENV_SEGMENT_SOURCE_KEY=topasshelmlintstrict
export ENV_TIAM_AUTH_DB_NAME=topasshelmlintstrict
export ENV_LAG_MINS=topasshelmlintstrict
